### ISSUE TITLE
LAION Aesthetics 6.5+ Not Available

### ISSUE THREAD

**Issue by D0miH** [LAION-AI/laion-datasets#9]
Hello,
I wanted to download the LAION Aesthetics V2 6.5+ dataset from Hugging Face. But unfortunately, the Hugging Face site of @christophschuhmann seems to be not available anymore.

Is there the possibility to get the dataset somewhere else? Or will the Hugging Face site will be made available again?

Thank you and best,
Dominik

**Comment by sanbuphy** [comment]
same

**Comment by rom1504** [comment]
https://laion.ai/notes/laion-maintanence/

**Comment by D0miH** [comment]
Sorry for the late reply. 
Thanks, at this point I was not aware of that.

**Comment by RunpuWei** [comment]
> Sorry for the late reply. Thanks, at this point I was not aware of that.

I need this data set now, I searched the Internet but could not find the image with the original file name😭😭😭. Do you have any access to obtain it? Thank you very much!!
